export const ROUTE = {
  HOME: 'HOME',
  NFCBLINK: 'NFCBLINK',
  PINPAGE: 'PINPAGE',
  CARDPAGE: 'CARDPAGE',
  CARDRESULT: 'CARDRESULT',
  ERRORPAGE: 'ERRORPAGE',
  DISCLAIMER: 'DISCLAIMER',
  RESGISTER: "RESGISTER"
};

export const langKey = '@lng';